//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaTime.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaTime.Localization.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HomeViewModel_About {
            get {
                return ResourceManager.GetString("HomeViewModel_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chances are, you come to us, because you are looking for a website where you can see new movies or get pleasure from watching the good old movies. Website BRB.TO - a real treasure trove of video that you can download for free or watch online.
        ///    The Video presents an extremely wide range of multimedia content. Here you can watch movies, enjoy the music of the best clips, find your favorite TV shows, cartoons and more..
        /// </summary>
        public static string HomeViewModel_AboutText {
            get {
                return ResourceManager.GetString("HomeViewModel_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartoons.
        /// </summary>
        public static string HomeViewModel_Cartoons {
            get {
                return ResourceManager.GetString("HomeViewModel_Cartoons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartoonserials.
        /// </summary>
        public static string HomeViewModel_Cartoonserials {
            get {
                return ResourceManager.GetString("HomeViewModel_Cartoonserials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string HomeViewModel_Favorites {
            get {
                return ResourceManager.GetString("HomeViewModel_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films.
        /// </summary>
        public static string HomeViewModel_Films {
            get {
                return ResourceManager.GetString("HomeViewModel_Films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serials.
        /// </summary>
        public static string HomeViewModel_Serials {
            get {
                return ResourceManager.GetString("HomeViewModel_Serials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV shows.
        /// </summary>
        public static string HomeViewModel_TVShows {
            get {
                return ResourceManager.GetString("HomeViewModel_TVShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string HomeViewModel_Video {
            get {
                return ResourceManager.GetString("HomeViewModel_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сlips.
        /// </summary>
        public static string HomeViewModel_Сlips {
            get {
                return ResourceManager.GetString("HomeViewModel_Сlips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сoncerts.
        /// </summary>
        public static string HomeViewModel_Сoncerts {
            get {
                return ResourceManager.GetString("HomeViewModel_Сoncerts", resourceCulture);
            }
        }
    }
}
